// const host = "https://expense-tracker-app-knl1.onrender.com";
const host = "http://localhost:3500";
export const setAvatarAPI = `${host}/api/auth/setAvatar`;
export const registerAPI = `${host}/api/auth/register`;
export const loginAPI = `${host}/api/auth/login`;
export const addTransaction = `${host}/api/v1/addTransaction`;
export const getTransactions = `${host}/api/v1/getTransaction`;
export const editTransactions = `${host}/api/v1/updateTransaction`;
export const deleteTransactions = `${host}/api/v1/deleteTransaction`;
export const addBankAcc = `${host}/bank/addAccount`;
export const getBankAcc = `${host}/bank/getAccount`;
export const addGoal = `${host}/goal/addGoal`;
export const getGoals = `${host}/goal/getGoal`;
export const editGoals = `${host}/goal/updateGoal`;
export const deleteGoals = `${host}/goal/deleteGoal`